In [2]:
import numpy as np

# Question 1


In [6]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

#For question 1(a)
print(A+B)

#For question 1(b)
print(A @ B)

#For question 1(c)
print(3*A-2*B)


[[ 3  1]
 [-3  7]]
[[ 5  0]
 [-9 12]]
[[ 4 -7]
 [ 6  1]]


# Question 2

In [9]:
#For question 2(a)
det = round(np.linalg.det(A),2)
print(f"The determinant of matrix A is: {det}")

print()
#For question 2(b)
if(not det==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of matrix A is: 6.0

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


# Question 3


In [12]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


# Question 4

In [59]:

F = np.array([[4,1.5,100],[6,2.0,150]])
Pr = np.array([[20,30]])
F = np.column_stack([np.ones(F.shape[0]), F])
B = ((np.linalg.inv(F.T @ F) @ F.T) @ Pr)
X = np.array([[1,8,3.0,200]])
price = np.linalg.det(X @ B)
print(f"The price of the house X3 is: {price}")



LinAlgError: Singular matrix

In [57]:
import numpy as np

# Step 1: Define the features of the houses and the prices
F = np.array([[4, 1.5, 100],  # Features of House 1: square footage, number of rooms, age
              [6, 2.0, 150]]) # Features of House 2: square footage, number of rooms, age

# Prices of the houses
Pr = np.array([20, 30])  # Prices of House 1 and House 2

# Step 2: Add a column of ones for the intercept term
F = np.column_stack([np.ones(F.shape[0]), F])  # Adding 1 for bias (intercept)

# Step 3: Compute the regression coefficients (B) using the Normal Equation
B = np.linalg.inv(F.T @ F) @ F.T @ Pr

# Step 4: Define the features of the 3rd house
X = np.array([1, 8, 3.0, 200])  # House 3: intercept=1, square footage=8, rooms=3.0, age=200

# Step 5: Predict the price of the 3rd house
price = X @ B  # Matrix multiplication to get the predicted price

# Step 6: Output the result
print(f"The predicted price of the house X3 is: {price:.2f}")


LinAlgError: Singular matrix